stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "ndi-en-prod-frontend"
  DOCKER_IMAGE_TAG: $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  CI_PROJET: "ns-ndi-en-prod"
  GIT_DEPTH: "0"
  KUBE_CONTEXT: labs-iut-info/labsagent:labsagentiut
  KUBECTL: "kubectl --insecure-skip-tls-verify"
  K8S_NAMESPACE: ns-ndi-en-prod

.kube-context:
  before_script:
    - if [ -n "$KUBE_CONTEXT" ]; then kubectl config use-context "$KUBE_CONTEXT"; fi

build-frontend:
  stage: build
  tags:
    - docker
  image: docker:24.0
  services:
    - docker:24.0-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE_TAG ./front-app/
    - docker tag $DOCKER_IMAGE_TAG $CI_REGISTRY/$CI_PROJET/$DOCKER_IMAGE_TAG
    - docker push $CI_REGISTRY/$CI_PROJET/$DOCKER_IMAGE_TAG
  only:
    - main

deploy-frontend:
  stage: deploy
  extends: [ .kube-context ]
  tags:
    - docker
  environment:
    name: production
    url: ndi-en-prod-frontend.labs.iut-larochelle.fr
  image:
    name: forge-registry.iut-larochelle.fr/kubectl/kubectl-envsubst:1.34.1 
    entrypoint: [ "" ]
  script:
    - if ! $KUBECTL get ns | grep $K8S_NAMESPACE ; then $KUBECTL create namespace $K8S_NAMESPACE ; fi
    - $KUBECTL delete --ignore-not-found=true secret gitlab-auth --namespace=$K8S_NAMESPACE
    - $KUBECTL create secret docker-registry gitlab-auth --docker-server=$CI_REGISTRY  --docker-username=$CI_REGISTRY_USER --docker-password=$CI_JOB_TOKEN --namespace=$K8S_NAMESPACE
    - $KUBECTL delete --ignore-not-found=true -f k8s/
    - cat k8s/deployment.yml | envsubst | $KUBECTL apply -f -
    - cat k8s/service.yml | $KUBECTL apply -f -
    - cat k8s/ingress.yml | $KUBECTL apply -f -
  only:
    - main