services:
  dev:
    image: node:20
    working_dir: /app/front-app
    volumes:
      - ./front-app:/app/front-app
    ports:
      - "5173:5173"
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0"

  prod:
    build:
      context: ./front-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: react-app
    restart: unless-stopped
