apiVersion: v1
kind: Service
metadata:
  name: service-ndi-en-prod-backend-mariadb
  namespace: ns-ndi-en-prod
spec:
  selector:
    component: backend-mariadb
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
